# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c26c5b3e66816b1197ab7f9acfa5213be4e103f5f178ddf8b80eb5c336411ea0bf007d610dcec299d4c0e75d6ce3ded8d8847c351412b4406179d542d48927c8

test:
  secret_key_base: 8d9acd79dced3cb9c6285a26d28e4f59e50900b55436cab7b53d3ea6df70839d4b181a73531acdf103f9e82621b9bef1e04083fe37a683ce11ac4e7f6b2ac5f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
